name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 0
      COVERAGE_TOTAL: 80

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test code standard
        run: |
          python -m pytest test/code_style_check.py
      - name: Test with pytest
        run: |
          python -m pytest --ignore=test/test_coverage.py
      - name: Build coverage
        run: |
          coverage run -m --source=src pytest test/test_unet.py test/test_data_loader.py test/test_weighted_kappa.py
          coverage json
          python -m pytest test/test_coverage.py

